version: 2.1
executors:
  default:
    docker:
      - image: buildpack-deps:bionic-curl
  test-env:
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-7.0.0"
        type: string
    docker:
      - image: enumack/mitama-env:<< parameters.compiler >>

jobs:
  wandbox-test:
    description: Testing the library using wandbox
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-head"
        type: string
    executor: default
    steps:
      - checkout
      - run: curl -sLJO https://github.com/LoliGothick/cbt/releases/download/v0.5.2/cbt_linux_amd64.tar
      - run: tar -vzxf ./cbt_linux_amd64.tar
      - run: chmod +x ./cbt
      - run: ./cbt wandbox cpp src/overview.cpp --compiler=<< parameters.compiler >> --std=c++17 --boost=1.65.0 --sprout --warning --pedantic=errors
      - store_artifacts:
          path: /results/permlink
          destination: raw-test-output
      - store_artifacts:
          path: /results
  full-test:
    description: Testing the library using Catch2
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-7.0.0"
        type: string
    executor:
      name: test-env
      compiler: << parameters.compiler >>
    steps:
      - checkout
      - run: apt upgrade -y && apt update -y && apt install -y git
      - run: git submodule update --init --recursive
      - run: chmod +x ./mitama_build.sh
      - run: ./mitama_build.sh

workflows:
  build:
    jobs:
      - full-test:
          compiler: clang-8.0.0
      - full-test:
          compiler: clang-7.1.0
      - full-test:
          compiler: clang-7.0.1
      - full-test:
          compiler: clang-7.0.0
      - full-test:
          compiler: clang-6.0.1
      - full-test:
          compiler: clang-6.0.0
      - full-test:
          compiler: gcc-9.1
      - full-test:
          compiler: gcc-8.3
      - full-test:
          compiler: gcc-8.2
      - full-test:
          compiler: gcc-8.1
