version: 2.1
executors:
  default:
    docker:
      - image: buildpack-deps:bionic-curl
  test-env:
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-7.0.0"
        type: string
    docker:
      - image: enumack/mitama-env:<< parameters.compiler >>

jobs:
  test:
    description: Testing the library using Catch2
    parameters:
      compiler:
        description: "compiler-version"
        default: "clang-7.0.0"
        type: string
    executor:
      name: test-env
      compiler: << parameters.compiler >>
    steps:
      - checkout
      - run: apt upgrade -y && apt update -y && apt install -y git
      - run: git submodule sync && git submodule update --init --recursive --remote
      - run: mkdir -p build && cd build && cmake .. && make -j5 && ctest 2>&1 | tee ./ctset.log
  

workflows:
  build:
    jobs:
      - test:
          compiler: clang-8.0.0
      - test:
          compiler: clang-7.1.0
      - test:
          compiler: clang-7.0.1
      - test:
          compiler: clang-7.0.0
      - test:
          compiler: clang-6.0.1
      - test:
          compiler: clang-6.0.0
      - test:
          compiler: gcc-9.1
      - test:
          compiler: gcc-8.3
      - test:
          compiler: gcc-8.2
      - test:
          compiler: gcc-8.1
